"use strict";
exports.__esModule = true;
exports.FILE_EXTENSION = void 0;
var FILE_EXTENSION;
(function (FILE_EXTENSION) {
    FILE_EXTENSION["JSON"] = "json";
    FILE_EXTENSION["JS"] = "js";
    FILE_EXTENSION["COFFEE"] = "coffee";
    FILE_EXTENSION["HTML"] = "html";
    FILE_EXTENSION["TXT"] = "txt";
    FILE_EXTENSION["CSV"] = "csv";
    FILE_EXTENSION["PNG"] = "png";
    FILE_EXTENSION["JPG"] = "jpg";
    FILE_EXTENSION["JPEG"] = "jpeg";
    FILE_EXTENSION["GIF"] = "gif";
    FILE_EXTENSION["TIF"] = "tif";
    FILE_EXTENSION["TIFF"] = "tiff";
    FILE_EXTENSION["ZIP"] = "zip";
    FILE_EXTENSION["PDF"] = "pdf";
    FILE_EXTENSION["VCF"] = "vcf";
    FILE_EXTENSION["SVG"] = "svg";
    FILE_EXTENSION["XLS"] = "xls";
    FILE_EXTENSION["XLSX"] = "xlsx";
    FILE_EXTENSION["DOC"] = "doc";
    FILE_EXTENSION["DOCX"] = "docx";
    FILE_EXTENSION["MP3"] = "mp3";
})(FILE_EXTENSION = exports.FILE_EXTENSION || (exports.FILE_EXTENSION = {}));
